CRITICAL - 2023-05-19 14:46:13 --> Undefined variable $validation
in APPPATH\Views\auth\login.php on line 23.
 1 APPPATH\Views\auth\login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php', 23)
 2 SYSTEMPATH\View\View.php(213): include('C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 5 APPPATH\Controllers\AuthController.php(23): view('auth/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
CRITICAL - 2023-05-19 14:47:00 --> Undefined variable $validation
in APPPATH\Views\auth\login.php on line 23.
 1 APPPATH\Views\auth\login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php', 23)
 2 SYSTEMPATH\View\View.php(213): include('C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 5 APPPATH\Controllers\AuthController.php(23): view('auth/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
CRITICAL - 2023-05-19 14:47:13 --> Undefined variable $validation
in APPPATH\Views\auth\login.php on line 23.
 1 APPPATH\Views\auth\login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php', 23)
 2 SYSTEMPATH\View\View.php(213): include('C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 5 APPPATH\Controllers\AuthController.php(23): view('auth/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
CRITICAL - 2023-05-19 14:49:36 --> Undefined variable $validation
in APPPATH\Views\auth\login.php on line 23.
 1 APPPATH\Views\auth\login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php', 23)
 2 SYSTEMPATH\View\View.php(213): include('C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 5 APPPATH\Controllers\AuthController.php(23): view('auth/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
CRITICAL - 2023-05-19 14:54:10 --> Undefined variable $validation
in APPPATH\Views\auth\login.php on line 23.
 1 APPPATH\Views\auth\login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php', 23)
 2 SYSTEMPATH\View\View.php(213): include('C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 5 APPPATH\Controllers\AuthController.php(23): view('auth/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
CRITICAL - 2023-05-19 14:54:12 --> Undefined variable $validation
in APPPATH\Views\auth\login.php on line 23.
 1 APPPATH\Views\auth\login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php', 23)
 2 SYSTEMPATH\View\View.php(213): include('C:\\project\\latihan_codeigniter\\app\\Views\\auth\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 5 APPPATH\Controllers\AuthController.php(23): view('auth/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
CRITICAL - 2023-05-19 15:02:45 --> Invalid file: "layout/template.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layout/template.php')
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->render('layout/template', [], true)
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 4 APPPATH\Controllers\AuthController.php(23): view('auth/login', [...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
CRITICAL - 2023-05-19 15:02:50 --> Invalid file: "layout/template.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('layout/template.php')
 2 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->render('layout/template', [], true)
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('auth/login', [], true)
 4 APPPATH\Controllers\AuthController.php(23): view('auth/login', [...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->login()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:04:56 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:04:56 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:07:19 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:07:19 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:07:37 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:07:37 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:17:16 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:17:16 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:18:31 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:18:31 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:22:08 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:22:08 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:22:23 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:22:23 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:27:18 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:27:18 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:28:49 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:28:49 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:32:00 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:32:00 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:35:33 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:35:33 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:36:26 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:36:26 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:40:32 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:40:32 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:41:00 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:41:00 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:41:30 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:41:30 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:43:58 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:43:58 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
ERROR - 2023-05-19 15:46:12 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\project\latihan_codeigniter\app\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
#5 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
#6 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#7 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\project\latihan_codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\project\latihan_codeigniter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\project\\lati...')
#10 {main}
CRITICAL - 2023-05-19 15:46:12 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(606): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 APPPATH\Controllers\AuthController.php(30): CodeIgniter\Model->countAllResults(false)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AuthController->prosesLogin()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\project\\latihan_codeigniter\\public\\index.php')
